name: Build Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme rst2pdf
    
    - name: Build HTML documentation
      run: |
        sphinx-build -b html . _build/html
    
    - name: Build PDF documentation
      run: |
        sphinx-build -b pdf . _build/pdf
    
    - name: Upload HTML artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: _build/html/
    
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: pdf-docs
        path: _build/pdf/*.pdf
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
